[package]
name = "forge-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
forge-emit = { path = "../forge-emit" }
forge-aarch64 = { path = "../forge-aarch64" }
forge-ir = { path = "../forge-ir" }
forge-mem = { path = "../forge-mem" }
forge-opt = { path = "../forge-opt" }
forge-regalloc = { path = "../forge-regalloc" }
forge-syntax = { path = "../forge-syntax" }
forge-x64 = { path = "../forge-x64" }
