[package]
name = "forge-wasm-api"
version.workspace = true
edition.workspace = true

[dependencies]
forge-wasm = { path = "../forge-wasm" }
forge-ir = { path = "../forge-ir" }
forge-opt = { path = "../forge-opt" }
forge-syntax = { path = "../forge-syntax" }
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
